# Generated by Django 2.0.4 on 2018-04-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/images', verbose_name='Imagem'),
        ),
    ]
