# Generated by Django 2.0.4 on 2018-05-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20180430_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['name'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
