# Generated by Django 2.0.4 on 2018-06-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20180624_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lição',
            name='curso',
            field=models.ForeignKey(on_delete='CASCADE', related_name='licoes', to='cursos.Curso', verbose_name='Curso'),
        ),
    ]
