# Generated by Django 2.0.4 on 2018-05-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180524_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='users',
            new_name='user',
        ),
    ]
